### ISSUE TITLE
PYTHON

### ISSUE THREAD

**Issue by Super45coder** [Sreehari521/Alexa#1]
I don't know python...

**Comment by Sreehari521** [comment]
> I don't know python...

np , you can go

**Comment by N3RDIUM** [comment]
I know (a lot of) python!

**Comment by Sreehari521** [comment]
> I know (a lot of) python!

Then u can contribute with me

**Comment by N3RDIUM** [comment]
> > I know python!
> 
> 
> 
> Then u can contribute with me

Sure!

**Comment by N3RDIUM** [comment]
I have actually made an even better assistant, I will share the code to you on a repo, and send the link here.
The assistant I built has wakewords and all of that cool stuff.

**Comment by devashish2024** [comment]
I also know Python, but not much...For you, I've an tip!!
Open Command Prompt in your WIndows then type "pip install pygame" then wait a few minutes it installs PyGame Package to make Games with Python then in your File, Import pygame.
```python
import pygame
```

**Comment by Super45coder** [comment]
I have a chromebook, not a windows.
________________________________

**Comment by devashish2024** [comment]
Cool!! But I think that the Python isn't supported in Chrome Book. So Which type of File extensions you could open? Like .exe, .apk, .dmg. Which?

**Comment by Super45coder** [comment]
Yeah, I think I can use exe. I can also use png, jpeg, mp3, pdf, and maybe a couple more.
________________________________

**Comment by devashish2024** [comment]
Good!! EXE are Windows Executables!! Did you've command prompt?

**Comment by N3RDIUM** [comment]
I'm using something like pygame, it's called pyglet.

**Comment by Super45coder** [comment]
I don't understand
________________________________

**Comment by N3RDIUM** [comment]
> I have actually made an even better assistant, I will share the code to you on a repo, and send the link here.
> The assistant I built has wakewords and all of that cool stuff.

Here it is: [LINK](https://github.com/somePythonProgrammer/pion)

**Comment by N3RDIUM** [comment]
Hello, @Super45coder @Sreehari521 @e-coders @winner108 ?

**Comment by winner108** [comment]
hi
hello @all

**Comment by devashish2024** [comment]
Hi! 
To @somePythonProgrammer
Yeah!! I've searched on Google that How many Extensions are Supported in Chromebook. I've seen!! That's Really Cool!! EXE [ Windows Executables Applications ], Linux Apps, macOS Applications [ .dmg ] I Love that!! I'm using Windows, it's Okay!! You can download it now, but I don't know How to Download packages via pip.
In my Old Windows 7 From there I Upgraded to 10, Go to the Path wherever your File was and then Hold the Shif Key then Right-click, also single right-click and see which extra comes os Holding shift, if a new comes and contains "open" so click there and type "pip install pygame" or other format you would know and Wait a Few minutes then Start Coding With PyGame And make games!!
```python
import pygame
```
